# Via https://forum.cloudron.io/post/90343
name: Deploy website folder contents to Cloudron Surfer

# Runs on pushes targeting the default branch
on:
  push:
    branches: ["main"]
jobs:

  steps:
  - uses: actions/checkout@v3
  - name: Run Surfer Action
    uses: addnab/docker-run-action@v3
    with:
      image: git.9wd.eu/9wd/surfer-action:latest
      run: |
        surfer --version
        surfer put --token ${{ secrets.SURFER_TOKEN }} --server https://localhost.dwebyvr.org website/* /
